### PR TITLE
Fix binary operator parentheses bug.

### LINKED ISSUE #399: Incorrect binary expression generation in modcc with operators of same precedence.
Binary operation expressions with a binary sub-expression with the same operator precedence are incorrectly rendered.

| Expression | Rendered |
|--|--|
| `a/(b/c)` | `a/b/c` |
| `(a*b)/c` | `(a*b)/c` (redundant parentheses) |
| `a-(b-c)` | `a-b-c` |
| `a<(b>0)` | `a<b> 0` |

Common code across the C-printer and CUDA-printer gives the same errors for both back-ends.

### PR DESCRIPTION
**Pull request by halfflat**
Fixes #399.

Update `test_printers.cpp`:
* Fix compilation and scope management issues, and re-include in CMakeLists.txt.
* Update to use `verbose_print` (run-time verbosity).
* Apply expected output tests to `CPrinter` and `CUDAPrinter` outputs.

Address binary operation rendering issue:
* Move C-style expression rendering common to `CPrinter` and `CUDAPrinter` to a specialized `Visitor`, `CExprRenderer`.
* Use operator associativity to determine need for parentheses around sub-expressions of a binary expression.

### CODE REVIEW

File: modcc/cexpr_render.cpp [hunk 1]
```diff
@@ -0,0 +1,112 @@
+#include <ostream>
+#include <unordered_map>
+
+#include "cexpr_render.hpp"
+#include "error.hpp"
+
+void CExprRenderer::render_as_call(const char* sub, Expression* e) {
```
Comment (bcumming) [inline modcc/cexpr_render.cpp]: Can we use `emit` in place of `render`? Not because `render` is bad, but because we already use `emit` elsewhere in modcc.

File: modcc/token.hpp [hunk 2]
```diff
@@ -77,6 +77,15 @@ enum class tok {
     reserved, // placeholder for generating keyword lookup
 };
 
+namespace std {
+    // note: necessary before C++14 (refer: lwg dr#2148).
+    template <> struct hash<tok> {
```
Comment (bcumming) [inline modcc/token.hpp]: newline before `struct`

File: tests/modcc/test_printers.cpp [hunk 3]
```diff
@@ -1,55 +1,93 @@
...
+TEST(scalar_printer, statement) {
+    std::vector<testcase> testcases = {
+        {"y=x+3",            "y=x+3"},
+        {"y=y^z",            "y=std::pow(y,z)"},
+        {"y=exp((x/2) + 3)", "y=exp(x/2+3)"},
+        {"z=a/b/c",          "z=a/b/c"},
+        {"z=a/(b/c)",        "z=a/(b/c)"},
+        {"z=(a*b)/c",        "z=a*b/c"},
+        {"z=a-(b+c)",        "z=a-(b+c)"},
+        {"z=(a>0)<(b>0)",    "z=a>0<(b>0)"}
```
Comment (bcumming) [inline tests/modcc/test_printers.cpp]: How about a test for `z=a- -2` to test the case of subtracting a negative value.

File: modcc/cudaprinter.cpp [hunk 4]
```diff
@@ -708,43 +709,7 @@ void CUDAPrinter::visit(LocalVariable *e) {
...
-            buffer() << "log(";
-            e->expression()->accept(this);
-            buffer() << ")";
-            return;
-        default :
-            throw compiler_exception(
-                "CUDAPrinter unsupported unary operator " + yellow(token_string(e->op())),
-                e->location());
-    }
+    cexpr_render(e, buffer().text(), this);
```
Comment (bcumming) [inline modcc/cudaprinter.cpp]: Nice reduction of duplicated code.

File: modcc/cexpr_render.cpp (hunk 1 above)
Comment (halfflat) [reply modcc/cexpr_render.cpp]: Should I use `emit` in the class name and wrapper call as well? Easy enough to change.
