### PR TITLE
Fix depricated call warnings in CUDA 9

### LINKED ISSUE #379: Fix CUDA 9 warp intrinsics warnings
CUDA 9 introduced more sophisticated warp-level synchronization. Intrinsics like `__ballot` and `__shfl` were depricated to be replaced with more specific instructions like `__shfl_sync`.

We are getting warnings with CUDA 9, e.g.
```
/users/bcumming/repos/arbor/src/backends/gpu/kernels/reduce_by_key.hpp(92):
  warning: function "__ballot"
/cm/shared/apps/cuda-9.0/include/sm_20_intrinsics.h(407):
  here was declared deprecated ("__ballot() is deprecated in favor of __ballot_sync()
  and may be removed in a future release (Use -Wno-deprecated-declarations to suppress
  this warning).")
```

### PR DESCRIPTION
**Pull request by bcumming**
CUDA 9 introduced new, fine-grained, thread synchronization primitives.
In doing so, it introduced new forms of the warp intrinsics like `__shfl_up`, depricating the old symbols in the process.

It will be a while before we can use 9 as the default minimum, so we have to support compilers that expect the new and old behavior.

There are two options: wrap the intrinsics in question, or pass nvcc a flag to not issue warnings about depricated symbols. I go for the approach of wrapping, because I would rather keep the compiler warning turned on.

Fixes #379.

### CODE REVIEW

File: src/backends/gpu/kernels/reduce_by_key.hpp [hunk 1]
```diff
@@ -8,6 +8,43 @@ namespace gpu {
 
 namespace impl{
 
+constexpr unsigned mask_all = 0xFFFFFFFF;
```
Comment (apeyser) [inline src/backends/gpu/kernels/reduce_by_key.hpp]: Style question: would it be more readable to just have two regions in this file, a __CUDACC_VER_MAJOR < 9 and not with 3 definitions rather than this line-wise preprocessor testing?

File: src/backends/gpu/kernels/reduce_by_key.hpp [hunk 2]
```diff
@@ -22,6 +59,9 @@ unsigned rounddown_power_of_2(std::uint32_t i) {
 // with two 32 bit shuffles.
 // get_from_lane is a wrapper around __shfl() for both single and double
 // precision.
+// TODO: CUDA 9 provides a double precision version of __shfl that
```
Comment (apeyser) [inline src/backends/gpu/kernels/reduce_by_key.hpp]: Why not know with an #if test? Since anyhow we have a bunch of preprocessor tests for this?

Comment (bcumming) [reply src/backends/gpu/kernels/reduce_by_key.hpp]: Because it is another `#if` test, and I would rather just replace this wholesale when the time comes to use CUDA9.

File: src/backends/gpu/kernels/reduce_by_key.hpp (hunk 1 above)
Comment (bcumming) [reply src/backends/gpu/kernels/reduce_by_key.hpp]: Not too big of a deal, either way.
Two regions would make for 5 additional lines of code (remove 6, add 11), because the function prototypes would have to be replicated, which makes more room for cut and paste error.
This approach also makes it very clear that the only thing that varies is the intrinsic.
